version: '3.9'

services:
  request-evaluation:
    container_name: request-evaluation
    image: ghcr.io/devind-team/request-evaluation:latest
    command: poetry run uvicorn main:app --reload --host 0.0.0.0 --port 80
    # python -m alembic upgrade head
    restart: always
    ports:
      - '8095:80'
    env_file: .env

  email:
    container_name: email
    image: ghcr.io/devind-team/request-evaluation:latest
    command: poetry run python task.py
    restart: always
    env_file: .env