version: '3.9'

services:
  request-evaluation:
    container_name: request-evaluation
    build:
      context: .
      dockerfile: Dockerfile
    image: request-evaluation
    command: poetry run uvicorn main:app --reload --host 0.0.0.0 --port 80
    ports:
      - '8095:80'
    env_file: .env

  email:
    container_name: email
    build:
      context: .
      dockerfile: Dockerfile
    image: emaily
    command: poetry run python task.py
    env_file: .env